[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && pnpm build || npm run build"
  publish = "./dist"

[build.environment]
  NPM_FLAGS="--version"

[context.production.environment]
  NODE_VERSION = '17.8.0'

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[functions]
  node_bundler = "esbuild"
